name: CI

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Create package and deploy to google store 
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r build/extension.zip -d ./
      - name: Deploy to google chrome store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: leimfoalkfhhklaccdhhpcjjmileikkh
          zip: build/extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
